name: 🔌 API / Integration Issue
description: Report issues with the API server, endpoints, or integrations
title: "[API]: "
labels: ["api", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for reporting issues with the REST API server, endpoints, or external integrations.

  - type: dropdown
    id: api_component
    attributes:
      label: API Component
      description: Which part of the API is affected?
      options:
        - /analyze endpoint
        - /health endpoint
        - Request/Response format
        - Error handling
        - CORS configuration
        - Authentication (if implemented)
        - Web interface integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: request_method
    attributes:
      label: HTTP Method
      description: Which HTTP method is affected?
      options:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
        - All methods
    validations:
      required: true

  - type: input
    id: endpoint
    attributes:
      label: Endpoint URL
      description: The specific endpoint that has the issue
      placeholder: /analyze
    validations:
      required: true

  - type: textarea
    id: request_details
    attributes:
      label: Request Details
      description: Provide the exact request being made
      placeholder: |
        Method: POST
        URL: http://localhost:3000/analyze
        Headers: Content-Type: application/json
        Body: {"content": "Role: Electrician, Hours: 40, Wage: $55.00"}
    validations:
      required: true

  - type: textarea
    id: expected_response
    attributes:
      label: Expected Response
      description: What response did you expect?
      placeholder: |
        HTTP 200 OK
        {
          "status": "APPROVED",
          "explanation": "...",
          "findings": []
        }
    validations:
      required: true

  - type: textarea
    id: actual_response
    attributes:
      label: Actual Response
      description: What response did you actually get?
      placeholder: |
        HTTP 500 Internal Server Error
        {"error": "Something went wrong"}
    validations:
      required: true

  - type: dropdown
    id: response_code
    attributes:
      label: HTTP Status Code
      description: What HTTP status code was returned?
      options:
        - "200 OK"
        - "400 Bad Request"
        - "401 Unauthorized"
        - "403 Forbidden"
        - "404 Not Found"
        - "500 Internal Server Error"
        - "502 Bad Gateway"
        - "503 Service Unavailable"
        - Other
    validations:
      required: true

  - type: textarea
    id: error_logs
    attributes:
      label: Server Logs
      description: Any relevant server-side error logs
      render: shell
    validations:
      required: false

  - type: dropdown
    id: client_type
    attributes:
      label: Client Type
      description: What type of client is making the request?
      options:
        - curl
        - Postman
        - Web browser
        - Custom application
        - Frontend React app
        - Other
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: How to reproduce the issue
      placeholder: |
        1. Start the server: npm run serve
        2. Send POST request to /analyze
        3. Observe 500 error
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false
