name: ⚖️ Compliance Decision Error
description: Report incorrect compliance decisions (APPROVED/REVISE/REJECT)
title: "[COMPLIANCE]: "
labels: ["compliance", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for reporting incorrect compliance decisions. The WCP AI Agent should follow DBWD rules accurately.

  - type: dropdown
    id: decision_type
    attributes:
      label: Incorrect Decision Type
      description: What type of incorrect decision was made?
      options:
        - Should be APPROVED but got REJECT
        - Should be APPROVED but got REVISE
        - Should be REVISE but got APPROVED
        - Should be REVISE but got REJECT
        - Should be REJECT but got APPROVED
        - Should be REJECT but got REVISE
        - Missing findings that should be present
        - Incorrect finding details
    validations:
      required: true

  - type: textarea
    id: wcp_input
    attributes:
      label: WCP Input
      description: The exact WCP input that produced the incorrect decision
      placeholder: Role: Electrician, Hours: 40, Wage: $55.00
    validations:
      required: true

  - type: dropdown
    id: expected_decision
    attributes:
      label: Expected Decision
      description: What should the correct decision be?
      options:
        - APPROVED
        - REVISE
        - REJECT
    validations:
      required: true

  - type: dropdown
    id: actual_decision
    attributes:
      label: Actual Decision
      description: What decision did the system return?
      options:
        - APPROVED
        - REVISE
        - REJECT
    validations:
      required: true

  - type: textarea
    id: expected_findings
    attributes:
      label: Expected Findings
      description: What findings should have been included?
      placeholder: |
        - Overtime: Hours exceed 40/week
        - Underpay: Wage below DBWD rate
    validations:
      required: false

  - type: textarea
    id: actual_findings
    attributes:
      label: Actual Findings
      description: What findings were actually returned?
      placeholder: |
        - No findings returned
    validations:
      required: false

  - type: textarea
    id: explanation
    attributes:
      label: Why This is Incorrect
      description: Explain why the decision is wrong based on DBWD rules
      placeholder: According to DBWD rates, Electrician base rate is $51.69/hr. Since $55/hr is above this, it should be APPROVED, not REJECT.
    validations:
      required: true

  - type: textarea
    id: dbwd_reference
    attributes:
      label: DBWD Rule Reference
      description: Reference to the specific DBWD rule or rate being violated
      placeholder: DBWD Electrician Base Rate: $51.69/hr (as per current DBWD schedule)
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Mock Mode (OPENAI_API_KEY=mock)
        - Real API Key
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false
