name: 📊 DBWD Rate Update
description: Request updates to DBWD wage rates
title: "[DBWD]: Update rates for "
labels: ["dbwd", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to request updates to the hardcoded DBWD wage rates in the system.

  - type: dropdown
    id: update_type
    attributes:
      label: Update Type
      description: What type of rate update is needed?
      options:
        - New rate for existing role
        - Add new role
        - Update fringe benefits
        - Update overtime rules
        - Other rate change
    validations:
      required: true

  - type: dropdown
    id: role
    attributes:
      label: Role
      description: Which role is affected?
      options:
        - Electrician
        - Laborer
        - Add new role
      default: 0
    validations:
      required: true

  - type: input
    id: new_role_name
    attributes:
      label: New Role Name
      description: If adding a new role, specify the name
      placeholder: Carpenter
    validations:
      required: false

  - type: input
    id: base_rate
    attributes:
      label: Base Rate (per hour)
      description: The new base rate in USD
      placeholder: 55.00
    validations:
      required: true

  - type: input
    id: fringe_rate
    attributes:
      label: Fringe Rate (per hour)
      description: The new fringe benefit rate in USD
      placeholder: 35.00
    validations:
      required: false

  - type: input
    id: effective_date
    attributes:
      label: Effective Date
      description: When should these rates take effect?
      placeholder: 2024-01-01
    validations:
      required: true

  - type: textarea
    id: source
    attributes:
      label: Source of Rates
      description: Where did these rates come from?
      placeholder: "DBWD website update on 2024-01-01, link: https://dbwd.gov.gov/rates"
    validations:
      required: true

  - type: textarea
    id: additional_changes
    attributes:
      label: Additional Changes Needed
      description: Any other changes related to this rate update
      placeholder: Update documentation, test scenarios, etc.
    validations:
      required: false

  - type: checkboxes
    id: affected_areas
    attributes:
      label: Areas That Need Updates
      description: Check all that need to be updated with these new rates
      options:
        - label: Source code (wcp-tools.ts)
          required: false
        - label: Mock responses (mock-responses.ts)
          required: false
        - label: Test scenarios
          required: false
        - label: Documentation
          required: false
        - label: Showcase demo
          required: false
    validations:
      required: false
