name: 📚 Documentation Issue
description: Report issues with documentation or suggest improvements
title: "[DOCS]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for reporting documentation issues or requesting documentation improvements.

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: Which documentation is affected?
      options:
        - README.md
        - API Documentation
        - Setup/Installation Guide
        - Compliance Rules Documentation
        - Code Comments
        - Test Documentation
        - Showcase Demo
        - Architecture docs (CONTEXT.md, AGENTS.md)
        - Workflow docs (WORKFLOW.md)
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What type of documentation issue is this?
      options:
        - Information is incorrect
        - Information is missing
        - Information is unclear/confusing
        - Outdated information
        - Typo or grammar error
        - Broken link
        - Code example doesn't work
        - Request new documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where in the documentation is the issue?
      placeholder: docs/INDEX.md, section "Getting Started"
    validations:
      required: true

  - type: textarea
    id: current_content
    attributes:
      label: Current Content
      description: What does the documentation currently say?
      placeholder: "The documentation says to run `npm install` but this doesn't work"
    validations:
      required: true

  - type: textarea
    id: suggested_fix
    attributes:
      label: Suggested Fix
      description: What should the documentation say instead?
      placeholder: "Should say to run `npm install` in the project directory"
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: How does this documentation issue affect users?
      placeholder: Users cannot set up the project correctly and get errors
    validations:
      required: false

  - type: checkboxes
    id: willing_to_help
    attributes:
      label: I can help with
      description: Check if you're willing to help with this
      options:
        - label: Write the fix myself
          required: false
        - label: Review the proposed changes
          required: false
        - label: Test the updated documentation
          required: false
    validations:
      required: false
