name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: feature_category
    attributes:
      label: Feature Category
      description: What type of feature are you requesting?
      options:
        - Compliance Logic (new rules, validations)
        - API Enhancements (new endpoints, features)
        - Web Interface (UI/UX improvements)
        - Performance & Scalability
        - Integration (new systems, databases)
        - Documentation & Examples
        - Testing & Quality
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Currently, the system cannot handle multiple WCPs in a single request, requiring users to submit each one individually.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: Add a batch endpoint that accepts an array of WCP inputs and returns an array of compliance decisions.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: Could use multiple parallel requests, but this would be less efficient.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical - Blocks current use case
        - High - Major improvement needed
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: checkboxes
    id: implementation_areas
    attributes:
      label: Implementation Areas
      description: Which parts of the system would need changes?
      options:
        - label: Agent logic (compliance rules)
          required: false
        - label: API endpoints
          required: false
        - label: Database/Storage
          required: false
        - label: Web interface
          required: false
        - label: Mock responses
          required: false
        - label: Tests
          required: false
        - label: Documentation
          required: false
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How would we know this feature is complete?
      placeholder: |
        - [ ] Batch endpoint accepts array of WCPs
        - [ ] Returns array of decisions with same order
        - [ ] Handles mixed valid/invalid inputs gracefully
        - [ ] Includes tests for batch functionality
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, include mockups or examples
      placeholder: |
        Request: {"wcps": ["Role: Electrician, Hours: 40, Wage: $55.00", "Role: Laborer, Hours: 45, Wage: $30.00"]}
        Response: {"results": [{"status": "APPROVED"}, {"status": "REVISE"}]}
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false
